# Generated by Django 4.1.5 on 2023-01-18 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('fonte', models.CharField(blank=True, max_length=200)),
                ('provincia', models.CharField(blank=True, max_length=200)),
                ('comune', models.CharField(blank=True, max_length=200)),
                ('data_nascimento', models.DateField(blank=True)),
                ('paternidade', models.CharField(blank=True, max_length=200)),
                ('conjuge', models.CharField(blank=True, max_length=200)),
                ('data_casamento', models.DateField(blank=True)),
                ('matrimonio', models.CharField(blank=True, max_length=200)),
                ('chegada_ao_brasil', models.DateField(blank=True)),
                ('local_de_chegada', models.CharField(blank=True, max_length=200)),
                ('data_insercao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
